// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACalmOR2W-Sz6-Q7DTEoG4-wmWQSE6YFo',
    appId: '1:629054859101:web:bbd62549d1476189f4eab4',
    messagingSenderId: '629054859101',
    projectId: 'citytourscartagena-dev',
    authDomain: 'citytourscartagena-dev.firebaseapp.com',
    storageBucket: 'citytourscartagena-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPx6ari33jQP8GFKpxM5anhcEX2IIPM2I',
    appId: '1:629054859101:android:55eb90cdb60026c7f4eab4',
    messagingSenderId: '629054859101',
    projectId: 'citytourscartagena-dev',
    storageBucket: 'citytourscartagena-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhud15Ndt8rTVagklmlQa34FV-Kw6cHkk',
    appId: '1:629054859101:ios:85ed376e9230a69cf4eab4',
    messagingSenderId: '629054859101',
    projectId: 'citytourscartagena-dev',
    storageBucket: 'citytourscartagena-dev.firebasestorage.app',
    iosBundleId: 'com.example.citytourscartagena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhud15Ndt8rTVagklmlQa34FV-Kw6cHkk',
    appId: '1:629054859101:ios:85ed376e9230a69cf4eab4',
    messagingSenderId: '629054859101',
    projectId: 'citytourscartagena-dev',
    storageBucket: 'citytourscartagena-dev.firebasestorage.app',
    iosBundleId: 'com.example.citytourscartagena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACalmOR2W-Sz6-Q7DTEoG4-wmWQSE6YFo',
    appId: '1:629054859101:web:ddf6805ccc1e6cf4f4eab4',
    messagingSenderId: '629054859101',
    projectId: 'citytourscartagena-dev',
    authDomain: 'citytourscartagena-dev.firebaseapp.com',
    storageBucket: 'citytourscartagena-dev.firebasestorage.app',
  );

}