// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7vYMe90cXWkV_R72vVIT4dnRU-oojT5g',
    appId: '1:258997063737:web:70cf8632f46b517cc2bde8',
    messagingSenderId: '258997063737',
    projectId: 'citytourscartagena',
    authDomain: 'citytourscartagena.firebaseapp.com',
    storageBucket: 'citytourscartagena.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu8OYk8ONP8SwMTxccdyBWxLRk1twTUbI',
    appId: '1:258997063737:android:ff6bd8ba3d0cb9a8c2bde8',
    messagingSenderId: '258997063737',
    projectId: 'citytourscartagena',
    storageBucket: 'citytourscartagena.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrjG-Fda2G0z95fyO73B-IFfzWIV-50uQ',
    appId: '1:258997063737:ios:b5a79e2c80316706c2bde8',
    messagingSenderId: '258997063737',
    projectId: 'citytourscartagena',
    storageBucket: 'citytourscartagena.firebasestorage.app',
    iosBundleId: 'com.example.citytourscartagena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrjG-Fda2G0z95fyO73B-IFfzWIV-50uQ',
    appId: '1:258997063737:ios:b5a79e2c80316706c2bde8',
    messagingSenderId: '258997063737',
    projectId: 'citytourscartagena',
    storageBucket: 'citytourscartagena.firebasestorage.app',
    iosBundleId: 'com.example.citytourscartagena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7vYMe90cXWkV_R72vVIT4dnRU-oojT5g',
    appId: '1:258997063737:web:e1090c344a9ab61ac2bde8',
    messagingSenderId: '258997063737',
    projectId: 'citytourscartagena',
    authDomain: 'citytourscartagena.firebaseapp.com',
    storageBucket: 'citytourscartagena.firebasestorage.app',
  );
}
